Add search shapes with search doc
newmediaresearch/vidispine-adapter pull request #47
Opened 2020-11-02 14:17 UTC by Laurence485

2020-11-05 11:49 UTC, marcuspen requested changes

2020-11-05 11:49 UTC, marcuspen commented on tests/test_search/test_search_shapes_with_search_doc.py
> +    }
I think better assertion would be:
```
expected_shape =  {
    "id": shape_id,
    "item": [{"id": item}],
    "metadata": {
        "field": [
            {
                "key": "test",
                "value": "test"
            }
        ]
    },
}
assert expected_shape in result['shape']
```
Remember we want to be as accurate as we can with assertions where we can. We also want them to be as readable as possible which means avoiding digging into multiple layers of a payload.

2020-11-05 11:49 UTC, marcuspen commented on tests/test_search/test_search_shapes_with_search_doc.py
> +    }
rather than repeating this over and over, why not put it in a `shape_search_metadata` fixture?

2020-11-05 14:45 UTC, Laurence485 commented on tests/test_search/test_search_shapes_with_search_doc.py
> +    }
agreed

2020-11-05 14:46 UTC, Laurence485 commented on vidispine/search.py
> +    ) -> BaseJson:
`search.html` endpoint needs fixing with sphinx

2020-11-06 09:35 UTC, marcuspen approved these changes

2020-11-06 09:40 UTC, merged