add Metadata class and update method
newmediaresearch/vidispine-adapter pull request #53
Opened 2020-11-04 14:02 UTC by Laurence485

2020-11-04 14:05 UTC, Laurence485 commented on vidispine/metadata.py
> +        self.entity = entity
This probably isn't ideal, but I can't set `entity = ''` and adjust the endpoint accordingly without raising the `NotImplementedError` from `EntityBase`.

2020-11-12 11:58 UTC, marcuspen requested changes

2020-11-12 11:58 UTC, marcuspen commented on vidispine/metadata.py
> +class Metadata(EntityBase):
Remove `EntityBase` from this class

2020-11-12 11:58 UTC, marcuspen commented on vidispine/metadata.py
> +class Metadata(EntityBase):
As discussed, make `Collection` and `Item` inherit this class so that we can re-use the methods across both.

2020-11-13 14:35 UTC, marcuspen approved these changes

2020-11-13 15:06 UTC, merged